<a href="https://colab.research.google.com/github/Marlen8/My-first-work/blob/main/NumPy_project_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
file_path = "/content/KAG_Conversion_Data.csv"

In [ ]:
from IPython.core.display import display_pretty
data_str = np.genfromtxt(file_path , delimiter="," , skip_header=1, dtype = str )
data_float = np.genfromtxt(file_path , delimiter= "," , skip_header=1 , dtype = float) 

In [ ]:
 #step 2
xyzcampaignid = np.array(data[:,1])
print (xyzcampaignid)
print((np.unique(xyzcampaignid, return_counts=True)))

 #clicks = np.array(data[:,7])
 #print (clicks)

[ 916.  916.  916. ... 1178. 1178. 1178.]
(array([ 916.,  936., 1178.]), array([ 54, 464, 625]))


In [ ]:
#step 3
age= data_str [:,3]
print(age.dtype)
print(np.unique(age))


<U11
['30-34' '35-39' '40-44' '45-49']


In [ ]:
np.min(age)

nan

In [ ]:
#step 4
spend = np.array(data_float[:,8])
min_spend = spend.min()
print (min_spend)
max_spend = spend.max()
print (max_spend)
avr_spend = spend.mean()
print(avr_spend)

0.0
639.9499981
51.36065613141295


In [ ]:
#step 5
clicks = np.array(data[:,7])
print (clicks)
max_click = clicks.max()
print (max_click)
index_max_click = list(clicks).index(clicks.max())
print(index_max_click)


id=np.array(data_str[:,0])
print (id[index_max_click])

In [ ]:
#step 6
product_bought = np.array(data_float[:,10])
print(product_bought[index_max_click])
print(product_bought.max())
product_bought_list = list(product_bought)
index_product_bought_max = product_bought_list.index(product_bought.max())
print(index_product_bought_max)


13.0
21.0
528


In [ ]:
arr1 = np.array([25,56,12,85,34,75])
print(arr1.shape)
arr2=np.array([42,3,86,32,856,46])
narr=np.random.rand(6)
print(narr)

(6,)
[0.27628353 0.27652127 0.00552126 0.78901574 0.71987368 0.47360711]


In [ ]:
arr1.astype("complex")

array([25.+0.j, 56.+0.j, 12.+0.j, 85.+0.j, 34.+0.j, 75.+0.j])